# Generated by Django 6.0.4 on 2026-04-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_payout_failure_reason_idempotencykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payout',
            name='last_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
