# Generated by Django 5.2.13 on 2026-04-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0004_ledgerentry_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='bank_account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
